// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetUserById`. */
export interface IGetUserByIdResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

/** Result of query `GetUserByEmailNormalized`. */
export interface IGetUserByEmailNormalizedResult {
    id: string;
    name: string;
    email: string;
    email_normalized: string;
    password_hash: string;
    created_at: Date;
}

/** Result of query `CreateUser`. */
export interface ICreateUserResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

export interface Queries {
    GetUserById: IGetUserByIdResult;
    GetUserByEmailNormalized: IGetUserByEmailNormalizedResult;
    CreateUser: ICreateUserResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
