// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateAttachment`. */
export interface ICreateAttachmentResult {
    id: string;
    message_id: string;
    kind: string;
    name: string | null;
    mime: string | null;
    created_at: Date;
}

/** Result of query `ListAttachmentsForMessage`. */
export interface IListAttachmentsForMessageResult {
    id: string;
    message_id: string;
    kind: string;
    name: string | null;
    mime: string | null;
    bytes: Uint8Array;
    created_at: Date;
}

/** Result of query `CreateConversation`. */
export interface ICreateConversationResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    reasoning_effort: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetConversationById`. */
export interface IGetConversationByIdResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    reasoning_effort: string | null;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListConversationsForUser`. */
export interface IListConversationsForUserResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    reasoning_effort: string | null;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetConversationCurrNode`. */
export interface ISetConversationCurrNodeResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    reasoning_effort: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `UpdateConversationModelSettings`. */
export interface IUpdateConversationModelSettingsResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    reasoning_effort: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `DeleteConversation`. */
export interface IDeleteConversationResult {
    id: string;
}

/** Result of query `CreateImportedConversation`. */
export interface ICreateImportedConversationResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    reasoning_effort: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetConversationSeedState`. */
export interface ISetConversationSeedStateResult {
    id: string;
}

/** Result of query `FindConversationMatch`. */
export interface IFindConversationMatchResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    reasoning_effort: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `CreateMcpServer`. */
export interface ICreateMcpServerResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetMcpServerForUser`. */
export interface IGetMcpServerForUserResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListMcpServersForUser`. */
export interface IListMcpServersForUserResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `UpdateMcpServer`. */
export interface IUpdateMcpServerResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetMcpServerEnabled`. */
export interface ISetMcpServerEnabledResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `DeleteMcpServer`. */
export interface IDeleteMcpServerResult {
}

/** Result of query `SetConversationMcpOverride`. */
export interface ISetConversationMcpOverrideResult {
    conversation_id: string;
    mcp_server_id: string;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListMcpServersWithOverride`. */
export interface IListMcpServersWithOverrideResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
    override_enabled: boolean | null;
}

/** Result of query `ListEnabledMcpServersForConversation`. */
export interface IListEnabledMcpServersForConversationResult {
    id: string;
    name: string;
    url: string;
    enabled: boolean;
    auto_approve: boolean;
    headers: unknown | null;
    request_timeout_ms: number;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `CreateMessage`. */
export interface ICreateMessageResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    tool_call_id: string | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `GetMessageById`. */
export interface IGetMessageByIdResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    tool_call_id: string | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `AppendMessageDeltas`. */
export interface IAppendMessageDeltasResult {
    id: string;
    content: string;
    reasoning_content: string | null;
}

/** Result of query `FinalizeMessage`. */
export interface IFinalizeMessageResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `ListMessageChildren`. */
export interface IListMessageChildrenResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `ListSiblings`. */
export interface IListSiblingsResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `UpdateMessageContent`. */
export interface IUpdateMessageContentResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `DeleteMessageSubtree`. */
export interface IDeleteMessageSubtreeResult {
    id: string;
}

/** Result of query `CreateImportedMessage`. */
export interface ICreateImportedMessageResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `SetMessageParentId`. */
export interface ISetMessageParentIdResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `GetActivePath`. */
export interface IGetActivePathResult {
    id: string | null;
    conversation_id: string | null;
    parent_id: string | null;
    role: string | null;
    content: string | null;
    reasoning_content: string | null;
    model: string | null;
    status: string | null;
    tool_calls: unknown | null;
    tool_call_id: string | null;
    timings: unknown | null;
    created_at: Date | null;
}

/** Result of query `CreateProvider`. */
export interface ICreateProviderResult {
    id: string | null;
    name: string | null;
    kind: string | null;
    base_url: string | null;
    api_key: string | null;
    default_model: string | null;
    models: string[] | null;
    model_metadata: unknown | null;
    oauth_credentials: unknown | null;
    enabled: boolean | null;
    created_at: Date | null;
    updated_at: Date | null;
}

/** Result of query `GetProviderById`. */
export interface IGetProviderByIdResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetProviderForUser`. */
export interface IGetProviderForUserResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListProvidersForUser`. */
export interface IListProvidersForUserResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetProviderEnabled`. */
export interface ISetProviderEnabledResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetProviderByNameForAccount`. */
export interface IGetProviderByNameForAccountResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `UpdateProvider`. */
export interface IUpdateProviderResult {
    id: string | null;
    name: string | null;
    kind: string | null;
    base_url: string | null;
    api_key: string | null;
    default_model: string | null;
    models: string[] | null;
    model_metadata: unknown | null;
    oauth_credentials: unknown | null;
    enabled: boolean | null;
    created_at: Date | null;
    updated_at: Date | null;
}

/** Result of query `UpdateProviderOauthCredentials`. */
export interface IUpdateProviderOauthCredentialsResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    models: string[];
    model_metadata: unknown;
    oauth_credentials: unknown | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `DeleteProvider`. */
export interface IDeleteProviderResult {
}

/** Result of query `InsertRunEvent`. */
export interface IInsertRunEventResult {
    run_id: string;
    seq: string;
    type: string;
    payload: unknown;
    created_at: Date;
}

/** Result of query `ListRunEventsAfter`. */
export interface IListRunEventsAfterResult {
    run_id: string;
    seq: string;
    type: string;
    payload: unknown;
    created_at: Date;
}

/** Result of query `DeleteExpiredRunEvents`. */
export interface IDeleteExpiredRunEventsResult {
    run_id: string;
    seq: string;
}

/** Result of query `CreateRun`. */
export interface ICreateRunResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetRunById`. */
export interface IGetRunByIdResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetRunStatus`. */
export interface ISetRunStatusResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `IncrementRunSeq`. */
export interface IIncrementRunSeqResult {
    id: string;
    seq: string;
}

/** Result of query `GetRunningRunForConversation`. */
export interface IGetRunningRunForConversationResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetBlockingRunForConversation`. */
export interface IGetBlockingRunForConversationResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetLatestRunForConversation`. */
export interface IGetLatestRunForConversationResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetRunLeafMessage`. */
export interface ISetRunLeafMessageResult {
    id: string;
    leaf_message_id: string | null;
}

/** Result of query `IncrementRunTurnCount`. */
export interface IIncrementRunTurnCountResult {
    id: string;
    turn_count: number;
}

/** Result of query `ListRunningRuns`. */
export interface IListRunningRunsResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `CreateToolApproval`. */
export interface ICreateToolApprovalResult {
    id: string;
    run_id: string;
    message_id: string;
    tool_call_id: string;
    tool_name: string;
    arguments: string;
    decision: string;
    created_at: Date;
    decided_at: Date | null;
}

/** Result of query `ListPendingApprovalsForRun`. */
export interface IListPendingApprovalsForRunResult {
    id: string;
    run_id: string;
    message_id: string;
    tool_call_id: string;
    tool_name: string;
    arguments: string;
    decision: string;
    created_at: Date;
    decided_at: Date | null;
}

/** Result of query `ListApprovalsForRun`. */
export interface IListApprovalsForRunResult {
    id: string;
    run_id: string;
    message_id: string;
    tool_call_id: string;
    tool_name: string;
    arguments: string;
    decision: string;
    created_at: Date;
    decided_at: Date | null;
}

/** Result of query `DecideRunApprovals`. */
export interface IDecideRunApprovalsResult {
    id: string;
    run_id: string;
    message_id: string;
    tool_call_id: string;
    tool_name: string;
    arguments: string;
    decision: string;
    created_at: Date;
    decided_at: Date | null;
}

/** Result of query `GetUserById`. */
export interface IGetUserByIdResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

/** Result of query `GetUserByEmailNormalized`. */
export interface IGetUserByEmailNormalizedResult {
    id: string;
    name: string;
    email: string;
    email_normalized: string;
    password_hash: string;
    created_at: Date;
}

/** Result of query `CreateUser`. */
export interface ICreateUserResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

export interface Queries {
    CreateAttachment: ICreateAttachmentResult;
    ListAttachmentsForMessage: IListAttachmentsForMessageResult;
    CreateConversation: ICreateConversationResult;
    GetConversationById: IGetConversationByIdResult;
    ListConversationsForUser: IListConversationsForUserResult;
    SetConversationCurrNode: ISetConversationCurrNodeResult;
    UpdateConversationModelSettings: IUpdateConversationModelSettingsResult;
    DeleteConversation: IDeleteConversationResult;
    CreateImportedConversation: ICreateImportedConversationResult;
    SetConversationSeedState: ISetConversationSeedStateResult;
    FindConversationMatch: IFindConversationMatchResult;
    CreateMcpServer: ICreateMcpServerResult;
    GetMcpServerForUser: IGetMcpServerForUserResult;
    ListMcpServersForUser: IListMcpServersForUserResult;
    UpdateMcpServer: IUpdateMcpServerResult;
    SetMcpServerEnabled: ISetMcpServerEnabledResult;
    DeleteMcpServer: IDeleteMcpServerResult;
    SetConversationMcpOverride: ISetConversationMcpOverrideResult;
    ListMcpServersWithOverride: IListMcpServersWithOverrideResult;
    ListEnabledMcpServersForConversation: IListEnabledMcpServersForConversationResult;
    CreateMessage: ICreateMessageResult;
    GetMessageById: IGetMessageByIdResult;
    AppendMessageDeltas: IAppendMessageDeltasResult;
    FinalizeMessage: IFinalizeMessageResult;
    ListMessageChildren: IListMessageChildrenResult;
    ListSiblings: IListSiblingsResult;
    UpdateMessageContent: IUpdateMessageContentResult;
    DeleteMessageSubtree: IDeleteMessageSubtreeResult;
    CreateImportedMessage: ICreateImportedMessageResult;
    SetMessageParentId: ISetMessageParentIdResult;
    GetActivePath: IGetActivePathResult;
    CreateProvider: ICreateProviderResult;
    GetProviderById: IGetProviderByIdResult;
    GetProviderForUser: IGetProviderForUserResult;
    ListProvidersForUser: IListProvidersForUserResult;
    SetProviderEnabled: ISetProviderEnabledResult;
    GetProviderByNameForAccount: IGetProviderByNameForAccountResult;
    UpdateProvider: IUpdateProviderResult;
    UpdateProviderOauthCredentials: IUpdateProviderOauthCredentialsResult;
    DeleteProvider: IDeleteProviderResult;
    InsertRunEvent: IInsertRunEventResult;
    ListRunEventsAfter: IListRunEventsAfterResult;
    DeleteExpiredRunEvents: IDeleteExpiredRunEventsResult;
    CreateRun: ICreateRunResult;
    GetRunById: IGetRunByIdResult;
    SetRunStatus: ISetRunStatusResult;
    IncrementRunSeq: IIncrementRunSeqResult;
    GetRunningRunForConversation: IGetRunningRunForConversationResult;
    GetBlockingRunForConversation: IGetBlockingRunForConversationResult;
    GetLatestRunForConversation: IGetLatestRunForConversationResult;
    SetRunLeafMessage: ISetRunLeafMessageResult;
    IncrementRunTurnCount: IIncrementRunTurnCountResult;
    ListRunningRuns: IListRunningRunsResult;
    CreateToolApproval: ICreateToolApprovalResult;
    ListPendingApprovalsForRun: IListPendingApprovalsForRunResult;
    ListApprovalsForRun: IListApprovalsForRunResult;
    DecideRunApprovals: IDecideRunApprovalsResult;
    GetUserById: IGetUserByIdResult;
    GetUserByEmailNormalized: IGetUserByEmailNormalizedResult;
    CreateUser: ICreateUserResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
