// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateAttachment`. */
export interface ICreateAttachmentResult {
    id: string;
    message_id: string;
    kind: string;
    name: string | null;
    mime: string | null;
    created_at: Date;
}

/** Result of query `ListAttachmentsForMessage`. */
export interface IListAttachmentsForMessageResult {
    id: string;
    message_id: string;
    kind: string;
    name: string | null;
    mime: string | null;
    bytes: Uint8Array;
    created_at: Date;
}

/** Result of query `CreateConversation`. */
export interface ICreateConversationResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetConversationById`. */
export interface IGetConversationByIdResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListConversationsForUser`. */
export interface IListConversationsForUserResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetConversationCurrNode`. */
export interface ISetConversationCurrNodeResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `CreateImportedConversation`. */
export interface ICreateImportedConversationResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `FindConversationMatch`. */
export interface IFindConversationMatchResult {
    id: string;
    user_id: string;
    title: string | null;
    provider_id: string | null;
    model: string | null;
    curr_node: string | null;
    pinned: boolean;
    forked_from_conversation_id: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `CreateMessage`. */
export interface ICreateMessageResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `GetMessageById`. */
export interface IGetMessageByIdResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `ListMessageChildren`. */
export interface IListMessageChildrenResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `CreateImportedMessage`. */
export interface ICreateImportedMessageResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `SetMessageParentId`. */
export interface ISetMessageParentIdResult {
    id: string;
    conversation_id: string;
    parent_id: string | null;
    role: string;
    content: string;
    reasoning_content: string | null;
    model: string | null;
    status: string;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date;
}

/** Result of query `GetActivePath`. */
export interface IGetActivePathResult {
    id: string | null;
    conversation_id: string | null;
    parent_id: string | null;
    role: string | null;
    content: string | null;
    reasoning_content: string | null;
    model: string | null;
    status: string | null;
    tool_calls: unknown | null;
    timings: unknown | null;
    created_at: Date | null;
}

/** Result of query `CreateProvider`. */
export interface ICreateProviderResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetProviderById`. */
export interface IGetProviderByIdResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `ListProviders`. */
export interface IListProvidersResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetProviderEnabled`. */
export interface ISetProviderEnabledResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetProviderByName`. */
export interface IGetProviderByNameResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `UpdateProvider`. */
export interface IUpdateProviderResult {
    id: string;
    name: string;
    kind: string;
    base_url: string;
    api_key: string | null;
    default_model: string | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `DeleteProvider`. */
export interface IDeleteProviderResult {
}

/** Result of query `CreateRun`. */
export interface ICreateRunResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetRunById`. */
export interface IGetRunByIdResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `SetRunStatus`. */
export interface ISetRunStatusResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `IncrementRunSeq`. */
export interface IIncrementRunSeqResult {
    id: string;
    seq: string;
}

/** Result of query `ListRunningRuns`. */
export interface IListRunningRunsResult {
    id: string;
    conversation_id: string;
    status: string;
    leaf_message_id: string | null;
    turn_count: number;
    budget: unknown | null;
    error: string | null;
    seq: string;
    created_at: Date;
    updated_at: Date;
}

/** Result of query `GetUserById`. */
export interface IGetUserByIdResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

/** Result of query `GetUserByEmailNormalized`. */
export interface IGetUserByEmailNormalizedResult {
    id: string;
    name: string;
    email: string;
    email_normalized: string;
    password_hash: string;
    created_at: Date;
}

/** Result of query `CreateUser`. */
export interface ICreateUserResult {
    id: string;
    name: string;
    email: string;
    created_at: Date;
}

export interface Queries {
    CreateAttachment: ICreateAttachmentResult;
    ListAttachmentsForMessage: IListAttachmentsForMessageResult;
    CreateConversation: ICreateConversationResult;
    GetConversationById: IGetConversationByIdResult;
    ListConversationsForUser: IListConversationsForUserResult;
    SetConversationCurrNode: ISetConversationCurrNodeResult;
    CreateImportedConversation: ICreateImportedConversationResult;
    FindConversationMatch: IFindConversationMatchResult;
    CreateMessage: ICreateMessageResult;
    GetMessageById: IGetMessageByIdResult;
    ListMessageChildren: IListMessageChildrenResult;
    CreateImportedMessage: ICreateImportedMessageResult;
    SetMessageParentId: ISetMessageParentIdResult;
    GetActivePath: IGetActivePathResult;
    CreateProvider: ICreateProviderResult;
    GetProviderById: IGetProviderByIdResult;
    ListProviders: IListProvidersResult;
    SetProviderEnabled: ISetProviderEnabledResult;
    GetProviderByName: IGetProviderByNameResult;
    UpdateProvider: IUpdateProviderResult;
    DeleteProvider: IDeleteProviderResult;
    CreateRun: ICreateRunResult;
    GetRunById: IGetRunByIdResult;
    SetRunStatus: ISetRunStatusResult;
    IncrementRunSeq: IIncrementRunSeqResult;
    ListRunningRuns: IListRunningRunsResult;
    GetUserById: IGetUserByIdResult;
    GetUserByEmailNormalized: IGetUserByEmailNormalizedResult;
    CreateUser: ICreateUserResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
